---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics-custom-resource-capv
  labels:
    kube-state-metrics/aggregate-to-manager: "true"
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - vsphereclusters
  - vsphereclusteridentities
  - vspheredeploymentzones
  - vspherefailuredomains
  - vspheremachines
  - vspherevms
  verbs:
  - get
  - list
  - watch