apiVersion: ipam.cluster.x-k8s.io/v1alpha1
kind: IPAddressClaim
metadata:
  name: ${IPCLAIM_NAME}
  annotations:
    prow.k8s.io/build-id: "${BUILD_ID}"
    prow.k8s.io/job: "${JOB_NAME}"
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: InClusterIPPool
    name: capv-e2e-ippool
